### ISSUE TITLE
Skips modal and automatically connects to Metamask

### ISSUE THREAD

**Issue by JUDOKICK** [Web3Modal/web3modal#131]
The latest version of web3modal seems to skip past the modal and issue a connect command to the injected provider. In my case being Metamask. Am I missing something or is this normal behaviour ?

On the same note, the modal displays as empty when running under incognito without Metamask

**Comment by JUDOKICK** [comment]
Update, the cause of the modal being blank is from providerOptions in the new Web3Modal. 

I had     

this.web3Modal = new Web3Modal({
      network: 'rinkeby',
      cacheProvider: false,
      disableInjectedProvider: false,
      providerOptionsModal
    })

Corrected to 

this.web3Modal = new Web3Modal({
      network: 'rinkeby',
      cacheProvider: false,
      disableInjectedProvider: false,
      providerOptions
    })

**Comment by pedrouid** [comment]
Glad you managed to fix it! 🙌

**Comment by JUDOKICK** [comment]
Hey Pedro, I am still having the automatic connection to metamask issue though.

**Comment by pedrouid** [comment]
If its connecting automatically to Metamask is because its the only provider available.The modal is only displayed if multiple options are configured.

Possible causes can be either the `providerOptions` is an empty object or the one of the `providerOptions` is not configured correctly. Make sure the required parameters for each `providerOptions` are met.

For example, WalletConnect provider will only be displayed if the infuraId is provided.

**Comment by JUDOKICK** [comment]
Yeah I believe I also the modal display has been resolved now with the same solution.

**Comment by pedrouid** [comment]
Awesome! 🙌
