### ISSUE TITLE
Walletconnect: how about not requiring infuraId ?

### ISSUE THREAD

**Issue by losnappas** [Web3Modal/web3modal#141]
Hey,

I've been developing a [WordPress plugin for web3 logins](https://wordpress.org/plugins/ethpress/). The plugin does just that: logins. I don't need the infuraId for anything, since I'm only using `enable` and `personalSign`. I tried setting it as `''`, but then that starts spamming requests every 1 seconds.

I created a web3-login component for just logins, but I realized that that's probably mostly gonna be a waste of effort, so I'd rather migrate to web3modal here, bundle sizes be damned.

**Comment by miohtama** [comment]
You can WalletConnect with any Ethereum node.

Instead of `infuraId`, you need to give `rpc` mappings.

For each chainId (mainnet, ropsten, etc.), give a respecting endpoint.

You can give a dummy URL if you are sure no RPC calls are going to happen.

More information here: 

https://www.npmjs.com/package/@walletconnect/web3-provider#custom-rpc-url

**Comment by losnappas** [comment]
Right, right, it's the walletconnect library that requires it, not this lib.
