### ISSUE TITLE
Hangs on .connect() in Chrome, works in other browsers

### ISSUE THREAD

**Issue by NemboKid** [Web3Modal/web3modal#244]
As many others here, I have problems with `await web3modal.connect()`, while `connectTo()` works fine. However, I only have this issue in Chrome, while in Brave and Firefox web3modal works perfect and lets me connect with metamask, portis or whatever I include in `providerOptions`.

The only response I get in Chrome is "Uncaught (in promise) undefined". And when catching promise, all I get is still just undefined. 

Problem with some chrome version, or why does only some people seem to have this issue?

**Comment by defi-david** [comment]
I was running into this issue as well and it turned out to be my toying around with adding custom providers that were not functional then removing them.  If you have `cacheProvider` set to `true`, then your browser will have `WEB3_CONNECT_CACHED_PROVIDER` set in its local storage.  Simply remove this key and you should be fine after that.
